### ISSUE TITLE
Any end-to-end examples out there?

### ISSUE THREAD

**Issue by chrisriesgo** [rdavisau/sockethelpers-for-pcl#1]
Hi @rdavisau. Do you have any end-to-end examples of using your sockethelpers? I tried spinning up a self-hosted thing last night, was able to connect, but couldn't get my messages to get picked up. I also have no idea what I'm doing :-P

**Comment by rdavisau** [comment]
Haha.. apologies, sockethelpers needs a bit of love but I have been a bit under the pump lately. 

I'll upload a new prerelease package with the latest changes and give you a quick write up of how you can use it and what caveats you need to be aware of. Hopefully I can get something up later tonight AU time! :+1:

**Comment by rdavisau** [comment]
Ok, I've pushed a new version of the sockethelpers alpha with a few improvements. I was hoping to do up a little demo app but what I have for now is [this LINQPad script](https://gist.github.com/rdavisau/e7aa53749e08e13329c6) which you can run/peruse to get an idea of how things work. In case you're not familiar with [LINQPad](http://www.linqpad.net/), if you save the gist to a .linq file, you can use the free version of LINQPad to open/run it without any issues.

The script simulates host and client side and demonstrates service discovery and typed messaging. The host sets up and starts listening, the client uses discovery to determine the location and port of the host service, then connects, sends a few messages and disconnects. The host dumps messages received to the results panel. I noticed just now that the Disconnected event is not firing, I'll look into that. I've sprinkled comments through the code so hopefully it helps a bit. 

My guess is you were probably pretty much there but got tripped up by any of the below (completely non-obvious, but hey it's alpha!) things:
- from my testing I think it turns out you _must_ add the assembly containing your message classes to the `AdditionalTypeResolutionAssemblies` property of `JsonProtocolMessenger` explicitly, or messages won't be resolved and you'll see nothing, unless you register an `ILogger` implementation (see end). Thinking about it I can probably make this happen automatically, so I'll look into that. 
- you have to call `StartExecuting` on a `JsonProtocolMessenger` for it to start working on the socket, otherwise you'll see nothing again. 

You can register an implementation of Splat's `ILogger` (see first line of script), and if you write out `Debug` level messages, you will see the individual send/receive operations of the json messenger. The type resolution error will also show in that case. 

Hopefully that gets you on the right track! Of course it's all early stage stuff but sockethelpers will get some more attention soon. If you have any suggestions, yell out :tada: Let me know how it goes.

**Comment by chrisriesgo** [comment]
Thanks, @rdavisau! About to give this a try.

**Comment by chrisriesgo** [comment]
@rdavisau - I copy/pasted the sample code into a Forms app (minus the LinqPad bits) and it ran great self-hosted. What might it look like to have the sample deployed to 2 devices passing messages back and forth? I tried it between a device and an emulator, but no luck. Again, I'm probably missing a piece of understanding

**Comment by rdavisau** [comment]
Hm, it should work OK! Do you know at what point it is failing?

My guess is that that depending on the platform and machine setup, your physical device and simulator may live on separate networks and the standard broadcast may not be propagating - if this were the case, for the example I provided, your client device would get stuck waiting at the discovery part. I'm still testing this stuff on different configs - sometimes standard broadcast works, sometimes it needs to be sent out on a per interface basis. You can try setting `SendOnAllInterfaces` on your service discoverer to true, that will change the way the discovery requests are sent. [I've updated the gist](https://gist.github.com/rdavisau/e7aa53749e08e13329c6/revisions) where you would make the change.

FYI there is [a bug](http://forums.xamarin.com/discussion/comment/120105/#Comment_120105) in System.Net on Android 4.4 for some physical devices that will prevent the above method from working, so if you do happen to be testing on that type of physical device be aware. 

Lastly, you can try swapping host and listener - you're more likely to have problems if the host is in the emulator (because your os may decide not to pass traffic to it from outside the machine), than if the host is on the physical network. If you have two physical devices, I expect you wont see this problem either. 

Let me know how you go.

**Comment by rdavisau** [comment]
Argh, I realised that there's one other issue that will cause problems moving to physical devices - the publisher sends back a hardcoded `"localhost"` string, which was fine for the LINQPad example. My plan is for the API to automatically return the address of the host that responded (it doesn't yet, oops), in the meantime, you can query for network adapters and return one using the `CommsInterface` class. This is not ideal and also not a perfect solution (on an emulator/simulator, if the device has access to all the computer interfaces, it may not send one that the physical device can reach) so I will make it automatic as soon as I get the chance.

```
public override Tuple<string,int> ResponseFor(string request)
{
    if (request == requestString)
    {
        // this is legit, let's send back our details
         var adapters = CommsInterface.GetAllInterfacesAsync().Result; // sigh async oversight
         var host = adapters.First(i=> i.IsUsable && !i.IsLoopback).IpAddress;

        return Tuple.Create(host, ServicePort);
    }
    else
    {
        // don't recognize this request, we might be getting hacked

        // if we returns null, nothing is sent back
        // it's as if no one was there.. 
        return null;
    }
}
```

**Comment by chrisriesgo** [comment]
Ah yeah. I was running the socket pcl sample app and noticed I could set
the IP directly while it defaulted to 127.0.0.1(locahost). I had to do that
to make the app work between device and emulator. So, your prognosis makes
sense.

**Comment by rdavisau** [comment]
Ok, I pushed an update to NuGet that has the library populate the remote host automatically. 
I've [updated the gist](https://gist.github.com/rdavisau/e7aa53749e08e13329c6/revisions). The discovery response class needs to implement a new interface called `IDiscoveryPayload`, which will be populated with the the remote host and address. Happy days!
